### ISSUE TITLE
sql script not working

### ISSUE THREAD

**Issue by zanac** [zayamatias/sscraper#2]
Using MariaDB 10.3.29 (debian buster):

MariaDB [romhashes]> CREATE TABLE 'filehashes' (                                                                                            
                         'file' varchar(300) NOT NULL,                                                                                      
                           'SHA1' varchar(100) DEFAULT NULL,                                                                                
                             'MD5' varchar(100) DEFAULT NULL,                                                                               
                               'CRC' varchar(100) DEFAULT NULL,                                                                             
                                 PRIMARY KEY ('file'),                                                                                      
                                   KEY 'filehashes_file_IDX' ('file') USING BTREE                                                           
                                   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4                                                                  
    ->                                                                                                                                      
    -> ;                                                                                                                                    
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syn
tax to use near ''filehashes' (                                                               ...' at line 1

**Comment by zayamatias** [comment]
Hi! 

Thanks for that! It seems there was an issue with the quoting, should be ok now (was using ' instead of `)

Let me know if it works.

**Comment by zayamatias** [comment]
No Feedback in 5 days, Assuming it is closed.
